source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"
gem "jekyll-gist"
gem "jemoji"
gem "kramdown-parser-gfm"
gem "webrick"
